name: nuban
version: 0.0.1
description: NUBAN is a library to validate account numbers in Nigerian banks as per the guidelines of CBN
homepage: https://github.com/lazymodifier/NUBAN
environment:
  sdk: '>=2.2.0 <3.0.0'